// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package rdbms

import (
	"database/sql"
	"time"
)

type ProductMetum struct {
	ProductID   string
	Name        string
	Symbol      string
	Description sql.NullString
	Type        string
	Exchange    string
	Location    sql.NullString
}

type StockPlatform struct {
	ProductID  string
	Platform   string
	Identifier string
}

type StoreLog struct {
	ProductID string
	StoredAt  time.Time
	Status    string
}
