// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: queries.sql

package rdbms

import (
	"context"
	"database/sql"
)

const checkStockExist = `-- name: CheckStockExist :one
SELECT EXISTS(SELECT 1 FROM product_meta WHERE product_id = ($1))
`

func (q *Queries) CheckStockExist(ctx context.Context, productID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkStockExist, productID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccessInfo = `-- name: CreateAccessInfo :exec
INSERT INTO store_log (product_id, "status") VALUES ($1, $2)
`

type CreateAccessInfoParams struct {
	ProductID string
	Status    string
}

func (q *Queries) CreateAccessInfo(ctx context.Context, arg CreateAccessInfoParams) error {
	_, err := q.db.ExecContext(ctx, createAccessInfo, arg.ProductID, arg.Status)
	return err
}

const getAllStockMetaList = `-- name: GetAllStockMetaList :many
SELECT product_id, "name", symbol, "description", "type", exchange,  "location"  FROM product_meta
`

func (q *Queries) GetAllStockMetaList(ctx context.Context) ([]ProductMetum, error) {
	rows, err := q.db.QueryContext(ctx, getAllStockMetaList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMetum
	for rows.Next() {
		var i ProductMetum
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Symbol,
			&i.Description,
			&i.Type,
			&i.Exchange,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockMeta = `-- name: GetStockMeta :one
SELECT product_id, "name", symbol, "description", "type", exchange,  "location"  FROM product_meta WHERE product_id = ($1)
`

func (q *Queries) GetStockMeta(ctx context.Context, productID string) (ProductMetum, error) {
	row := q.db.QueryRowContext(ctx, getStockMeta, productID)
	var i ProductMetum
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Location,
	)
	return i, err
}

const getStockMetaWithPlatform = `-- name: GetStockMetaWithPlatform :one
SELECT product_meta.product_id, "name", symbol, "description", "type", exchange,  "location" , platform, identifier 
FROM product_meta 
JOIN stock_platform 
ON product_meta.product_id = stock_platform.product_id 
WHERE product_meta.product_id = ($1)
`

type GetStockMetaWithPlatformRow struct {
	ProductID   string
	Name        string
	Symbol      string
	Description sql.NullString
	Type        string
	Exchange    string
	Location    sql.NullString
	Platform    string
	Identifier  string
}

func (q *Queries) GetStockMetaWithPlatform(ctx context.Context, productID string) (GetStockMetaWithPlatformRow, error) {
	row := q.db.QueryRowContext(ctx, getStockMetaWithPlatform, productID)
	var i GetStockMetaWithPlatformRow
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Location,
		&i.Platform,
		&i.Identifier,
	)
	return i, err
}

const insertNewStockMeta = `-- name: InsertNewStockMeta :exec
INSERT INTO product_meta (product_id, "name", symbol, "description", "type", exchange, "location") 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNewStockMetaParams struct {
	ProductID   string
	Name        string
	Symbol      string
	Description sql.NullString
	Type        string
	Exchange    string
	Location    sql.NullString
}

func (q *Queries) InsertNewStockMeta(ctx context.Context, arg InsertNewStockMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertNewStockMeta,
		arg.ProductID,
		arg.Name,
		arg.Symbol,
		arg.Description,
		arg.Type,
		arg.Exchange,
		arg.Location,
	)
	return err
}

const insertNewStockPlatformMeta = `-- name: InsertNewStockPlatformMeta :exec
INSERT INTO stock_platform (product_id, platform, identifier) VALUES ($1, $2, $3)
`

type InsertNewStockPlatformMetaParams struct {
	ProductID  string
	Platform   string
	Identifier string
}

func (q *Queries) InsertNewStockPlatformMeta(ctx context.Context, arg InsertNewStockPlatformMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertNewStockPlatformMeta, arg.ProductID, arg.Platform, arg.Identifier)
	return err
}

const updatePlatform = `-- name: UpdatePlatform :exec
UPDATE stock_platform SET platform = ($1), identifier = ($2) WHERE product_id = ($3)
`

type UpdatePlatformParams struct {
	Platform   string
	Identifier string
	ProductID  string
}

func (q *Queries) UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) error {
	_, err := q.db.ExecContext(ctx, updatePlatform, arg.Platform, arg.Identifier, arg.ProductID)
	return err
}
