// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.test.sql

package rdbms

import (
	"context"
)

const countTestTableEntity = `-- name: CountTestTableEntity :one
SELECT COUNT(*) FROM test_table
`

func (q *Queries) CountTestTableEntity(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTestTableEntity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTestTableEntity = `-- name: InsertTestTableEntity :exec
INSERT INTO test_table (id) VALUES (DEFAULT)
`

func (q *Queries) InsertTestTableEntity(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, insertTestTableEntity)
	return err
}
